### ISSUE TITLE
Resource Order

### ISSUE THREAD

**Issue by EagLeTaLoN713** [kibook/redm-webmap#4]
In what order should weathersync, httpmanager and wemap be in the resource? It seems like the webmap doesn't work half the time

**Comment by kibook** [comment]
The order you start them in server.cfg should be irrelevant, as those resources will always be started before this one automatically since they are listed as dependencies in fxmanifest.lua.

Can you elaborate on "doesn't work"? Do you receive an error message? What actually happens?

One thing that someone had an issue with recently was the URL. You **must** include the trailing / after the resource name, so be sure you are using:
```
http://[server IP]:[server port]/webmap/
```
and not
```
http://[server IP]:[server port]/webmap
```
If you leave off the trailing /, your web browser will not understand that relative URLs for supporting files like `script.js` should be relative to `/webmap/`, so it will try to request `/script.js` instead of `/webmap/script.js`. I'll have to look into whether it might be possible to automatically redirect to `/webmap/` if the trailing slash is omitted, but that's a change to httpmanager and not this resource.

If that isn't the issue you're having, then please provide some more details on what you're seeing.

**Comment by EagLeTaLoN713** [comment]
Great Thank you. it was the dreaded /    such a noob moment too because I remember reading it was needed. Thank you for your quick response.
